config/routes.rb
Rails.application.routes.draw do
  resources :minutes do
    resource :export, only: [:create], controller: 'minutes/export'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "minutes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/github_wiki_manager.rb
class GithubWikiManager
  WORKING_DIRECTORY = Rails.root.join('wiki_repositories').freeze

  def self.export_minute(minute)
    new.export_minute(minute)
  end

  def initialize
    @git = Dir.exist?(WORKING_DIRECTORY) ? Git.open(WORKING_DIRECTORY, log: Logger.new(STDOUT))
                                         : Git.clone(ENV['GITHUB_WIKI_URL'], WORKING_DIRECTORY)
    set_github_account
    create_credential_file
  end

  def set_github_account
    @git.config('user.name', ENV['GITHUB_USER_NAME'])
    @git.config('user.email', ENV['GITHUB_USER_EMAIL'])
  end

  def create_credential_file
    credential_file_path = Rails.root.join('.netrc')
    return if File.exist?(credential_file_path)

    content = <<-CREDENTIAL
machine github.com
login #{ENV['GITHUB_USER_NAME']}
password #{ENV['GITHUB_ACCESS_TOKEN']}
    CREDENTIAL

    File.open(credential_file_path, 'w+') do |file|
      file.puts content
    end
    File.chmod(0600, credential_file_path)
  end

  def export_minute(minute)
    # TODO: 例外が発生した時の処理を書く
    @git.pull
    commit_minute(minute)
    @git.push('origin', 'master')
  end

  def commit_minute(minute)
    filepath = "#{WORKING_DIRECTORY}/#{minute.title}.md"
    File.open(filepath, 'w+') do |file|
      file.puts minute.content # 実際のアプリでは、Markdownの末尾に空行があるため、writeでファイルに書き込む
    end

    @git.add("#{minute.title}.md")
    @git.commit("#{minute.title}.mdを作成")
  end
end

app/models/minute.rb
class Minute < ApplicationRecord
  def title
    formatted_date = meeting_date.strftime('%Y年%m月%d日')
    "ふりかえり・計画ミーティング#{formatted_date}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/minutes/export_controller.rb
class Minutes::ExportController < ApplicationController
  def create
    minute = Minute.find(params[:minute_id])
    GithubWikiManager.export_minute(minute)

    redirect_to minutes_url, notice: "GitHub Wikiに議事録を反映させました"
  end
end

app/controllers/minutes_controller.rb
class MinutesController < ApplicationController
  before_action :set_minute, only: %i[ show edit update destroy ]

  # GET /minutes or /minutes.json
  def index
    @minutes = Minute.all
  end

  # GET /minutes/1 or /minutes/1.json
  def show
  end

  # GET /minutes/new
  def new
    @minute = Minute.new
  end

  # GET /minutes/1/edit
  def edit
  end

  # POST /minutes or /minutes.json
  def create
    @minute = Minute.new(minute_params)

    respond_to do |format|
      if @minute.save
        format.html { redirect_to minute_url(@minute), notice: "Minute was successfully created." }
        format.json { render :show, status: :created, location: @minute }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @minute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /minutes/1 or /minutes/1.json
  def update
    respond_to do |format|
      if @minute.update(minute_params)
        format.html { redirect_to minute_url(@minute), notice: "Minute was successfully updated." }
        format.json { render :show, status: :ok, location: @minute }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @minute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /minutes/1 or /minutes/1.json
  def destroy
    @minute.destroy!

    respond_to do |format|
      format.html { redirect_to minutes_url, notice: "Minute was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_minute
      @minute = Minute.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def minute_params
      params.require(:minute).permit(:content, :meeting_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/minutes_helper.rb
module MinutesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExampleGithubWikiApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/minutes/_form.html.erb
<%= form_with(model: minute) do |form| %>
  <% if minute.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(minute.errors.count, "error") %> prohibited this minute from being saved:</h2>

      <ul>
        <% minute.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :meeting_date, style: "display: block" %>
    <%= form.date_field :meeting_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/minutes/_minute.html.erb
<div id="<%= dom_id minute %>">
  <p>
    <strong>Content:</strong>
    <%= minute.content %>
  </p>

  <p>
    <strong>Meeting date:</strong>
    <%= minute.meeting_date %>
  </p>

  <div>
    <%= link_to 'GitHub Wiki にエクスポート', minute_export_path(minute), data: { turbo_method: :post } %>
  </div>
</div>

app/views/minutes/edit.html.erb
<h1>Editing minute</h1>

<%= render "form", minute: @minute %>

<br>

<div>
  <%= link_to "Show this minute", @minute %> |
  <%= link_to "Back to minutes", minutes_path %>
</div>

app/views/minutes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Minutes</h1>

<div id="minutes">
  <% @minutes.each do |minute| %>
    <%= render minute %>
    <p>
      <%= link_to "Show this minute", minute %>
    </p>
  <% end %>
</div>

<%= link_to "New minute", new_minute_path %>

app/views/minutes/new.html.erb
<h1>New minute</h1>

<%= render "form", minute: @minute %>

<br>

<div>
  <%= link_to "Back to minutes", minutes_path %>
</div>

app/views/minutes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @minute %>

<div>
  <%= link_to "Edit this minute", edit_minute_path(@minute) %> |
  <%= link_to "Back to minutes", minutes_path %>

  <%= button_to "Destroy this minute", @minute, method: :delete %>
</div>